### ISSUE TITLE
Eliminate horizontal scrolling for mobile layouts

### ISSUE THREAD

**Issue by gmalpartida** [gmalpartida/ohmyfood#9]
home page how-it-works steps cause horizontal scrolling for mobile layouts

**Comment by nikibrown** [comment]
on .button-work get rid of your width: 600px

 Screenshot: https://shottr.cc/s/Fdwa/SCR-20240920-i8kp.png
 
 Screenshot https://shottr.cc/s/FhTa/SCR-20240920-i9zp.png
